/*=============================================================================
  METADATA Layer - ETL Configuration Table + Config Inserts
  Control plane for the metadata-driven stage loading framework
=============================================================================*/

USE SCHEMA IP_DATAENGINEERING.METADATA;

CREATE OR REPLACE TABLE ETL_CONFIG (
    CONFIG_ID           NUMBER AUTOINCREMENT,
    STAGE_TABLE_NAME    VARCHAR(200),
    SOURCE_SQL          VARCHAR(16000),
    PRIMARY_KEY_COLUMNS VARCHAR(500),
    SCD_TYPE            NUMBER(1),
    IS_ACTIVE           BOOLEAN DEFAULT TRUE,
    CREATED_DTS         TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_DTS         TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- STG_SERVER_SUMMARY: SCD Type 1 (overwrite)
INSERT INTO ETL_CONFIG (STAGE_TABLE_NAME, SOURCE_SQL, PRIMARY_KEY_COLUMNS, SCD_TYPE)
VALUES ('STG_SERVER_SUMMARY',
'SELECT S.SERVER_ID, S.SERVER_NAME, S.SERVER_TYPE, S.OS_NAME, S.OS_VERSION,
    S.CPU_CORES, S.RAM_GB, S.STORAGE_TB, S.IP_ADDRESS, S.SERVER_STATUS,
    S.ENVIRONMENT, S.OWNER_TEAM, S.PROVISIONED_DATE,
    D.DC_NAME, D.DC_LOCATION, D.DC_REGION, D.DC_TIER
FROM IP_DATAENGINEERING.RAW.SERVERS S
JOIN IP_DATAENGINEERING.RAW.DATA_CENTERS D ON S.DC_ID = D.DC_ID',
'SERVER_ID', 1);

-- STG_INFRA_ASSETS: SCD Type 2 (track history)
INSERT INTO ETL_CONFIG (STAGE_TABLE_NAME, SOURCE_SQL, PRIMARY_KEY_COLUMNS, SCD_TYPE)
VALUES ('STG_INFRA_ASSETS',
'SELECT N.DEVICE_ID, N.DEVICE_NAME, N.DEVICE_TYPE, N.MANUFACTURER, N.MODEL,
    N.FIRMWARE_VER, N.IP_ADDRESS, N.PORT_COUNT, N.THROUGHPUT_GBPS,
    N.DEVICE_STATUS, N.INSTALL_DATE, N.LAST_PATCHED,
    D.DC_NAME, D.DC_REGION, D.DC_TIER
FROM IP_DATAENGINEERING.RAW.NETWORK_DEVICES N
JOIN IP_DATAENGINEERING.RAW.DATA_CENTERS D ON N.DC_ID = D.DC_ID',
'DEVICE_ID', 2);

-- STG_INCIDENT_DETAIL: SCD Type 1 (overwrite)
INSERT INTO ETL_CONFIG (STAGE_TABLE_NAME, SOURCE_SQL, PRIMARY_KEY_COLUMNS, SCD_TYPE)
VALUES ('STG_INCIDENT_DETAIL',
'SELECT I.INCIDENT_ID, I.INCIDENT_TITLE, I.SEVERITY, I.INCIDENT_STATUS,
    I.CREATED_DATE, I.RESOLVED_DATE, I.ROOT_CAUSE, I.ASSIGNED_TEAM,
    I.RESOLUTION_TIME_HOURS,
    S.SERVER_NAME, S.ENVIRONMENT AS SERVER_ENVIRONMENT, S.OWNER_TEAM AS SERVER_OWNER_TEAM,
    A.APP_NAME, A.BUSINESS_UNIT, A.CRITICALITY AS APP_CRITICALITY
FROM IP_DATAENGINEERING.RAW.INCIDENTS I
LEFT JOIN IP_DATAENGINEERING.RAW.SERVERS S ON I.SERVER_ID = S.SERVER_ID
LEFT JOIN IP_DATAENGINEERING.RAW.APPLICATIONS A ON I.APP_ID = A.APP_ID',
'INCIDENT_ID', 1);

-- STG_APP_SERVER_MAP: SCD Type 1 (overwrite) - Composite PK: APP_ID + SERVER_ID
INSERT INTO ETL_CONFIG (STAGE_TABLE_NAME, SOURCE_SQL, PRIMARY_KEY_COLUMNS, SCD_TYPE)
VALUES ('STG_APP_SERVER_MAP',
'SELECT A.APP_ID, A.SERVER_ID, A.APP_NAME, A.APP_TYPE, A.CRITICALITY, A.BUSINESS_UNIT,
    S.SERVER_NAME, S.SERVER_TYPE, S.ENVIRONMENT, S.SERVER_STATUS,
    D.DC_NAME, D.DC_REGION
FROM IP_DATAENGINEERING.RAW.APPLICATIONS A
JOIN IP_DATAENGINEERING.RAW.SERVERS S ON A.SERVER_ID = S.SERVER_ID
JOIN IP_DATAENGINEERING.RAW.DATA_CENTERS D ON S.DC_ID = D.DC_ID',
'APP_ID|SERVER_ID', 1);
